    // unexpire passwords to avoid login issues
    new $namespace
    set $namespace = "%SYS"
    do ##class(Security.Users).UnExpireUserPasswords("*")

    set $namespace = "USER"

    // load source code
    do $SYSTEM.OBJ.LoadDir("/opt/irisapp/src", "ck", ,1)

    // start production
    set production = "Demo.Production"
    set ^Ens.Configuration("csp","LastProduction") = production
    do ##class(Ens.Director).SetAutoStart(production)

    set $namespace = "%SYS"
    
    halt